package org.xsc.pure

/*
 * Trait for internal actor state, desired to be immutable.
 *
 * Updates can only be performed in a pure way using effects generated by
 * impure logic (= commands),
 */
trait PureState[Effect, State <: PureState[Effect, State]] {
  def update(effect: Effect): State
}
